version: "3"
services:
  front:
    build:
      context: .
      dockerfile: docker/front
    ports:
      - "8080:80"
  back:
    build:
      context: .
      dockerfile: docker/back
    ports:
      - "10000:10000"